name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Update setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: Ahmad-shd
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"
